import tailwindcss from "@tailwindcss/vite";
import react from "@vitejs/plugin-react";
import { nitro } from "nitro/vite";
import { defineConfig } from "vite-plus";

export default defineConfig(({ mode: _mode }) => ({
  server: {
    host: true,
    port: 5173,
  },
  staged: {
    "*": "vp check --fix",
  },
  fmt: {},
  test: {
    include: ["src/**/*.test.ts", "sdk/**/*.test.ts"],
    environment: "node",
    testTimeout: 300_000,
    hookTimeout: 180_000,
    fileParallelism: false,
  },
  run: {
    tasks: {
      "forge:ensure": {
        command: "node scripts/ensure-forge.mjs",
        cache: false,
      },
      "forge:deps": {
        command: "node scripts/install-forge-deps.mjs",
        dependsOn: ["forge:ensure"],
        cache: false,
      },
      "forge:build": {
        command:
          'bash -lc "cd contracts && export PATH=\\"$HOME/.foundry/bin:$PATH\\" && forge build" && node scripts/export-foundry-abis.mjs',
        dependsOn: ["forge:deps"],
        input: [
          "contracts/foundry.toml",
          "contracts/src/**",
          "contracts/script/**",
          "contracts/test/**",
        ],
        output: ["contracts/out/**", "sdk/contracts/generated/**"],
      },
      "forge:test": {
        command:
          'bash -lc "cd contracts && export PATH=\\"$HOME/.foundry/bin:$PATH\\" && forge test"',
        dependsOn: ["forge:build"],
        cache: false,
      },
      "dev:stack": {
        command: "node scripts/dev-stack.mjs",
        dependsOn: ["forge:build"],
        cache: false,
      },
      "app:dev": {
        command: "vp dev",
        dependsOn: ["dev:stack"],
        cache: false,
      },
      "app:build": {
        command: "tsc && vp build",
        dependsOn: ["forge:build"],
        output: ["dist/**"],
      },
      "deploy:ethereum-sepolia": {
        command: "node scripts/deploy-ethereum-sepolia.mjs",
        dependsOn: ["forge:build"],
        cache: false,
      },
    },
  },
  lint: {
    plugins: ["oxc", "typescript", "unicorn", "react"],
    categories: {
      correctness: "warn",
    },
    env: {
      builtin: true,
    },
    ignorePatterns: [
      "dist",
      ".output",
      "contracts/out",
      "contracts/cache",
      "contracts/.cache",
      "sdk/contracts/generated",
    ],
    overrides: [
      {
        files: ["**/*.{ts,tsx}"],
        rules: {
          "constructor-super": "error",
          "for-direction": "error",
          "getter-return": "error",
          "no-async-promise-executor": "error",
          "no-case-declarations": "error",
          "no-class-assign": "error",
          "no-compare-neg-zero": "error",
          "no-cond-assign": "error",
          "no-const-assign": "error",
          "no-constant-binary-expression": "error",
          "no-constant-condition": "error",
          "no-control-regex": "error",
          "no-debugger": "error",
          "no-delete-var": "error",
          "no-dupe-class-members": "error",
          "no-dupe-else-if": "error",
          "no-dupe-keys": "error",
          "no-duplicate-case": "error",
          "no-empty": "error",
          "no-empty-character-class": "error",
          "no-empty-pattern": "error",
          "no-empty-static-block": "error",
          "no-ex-assign": "error",
          "no-extra-boolean-cast": "error",
          "no-fallthrough": "error",
          "no-func-assign": "error",
          "no-global-assign": "error",
          "no-import-assign": "error",
          "no-invalid-regexp": "error",
          "no-irregular-whitespace": "error",
          "no-loss-of-precision": "error",
          "no-misleading-character-class": "error",
          "no-new-native-nonconstructor": "error",
          "no-nonoctal-decimal-escape": "error",
          "no-obj-calls": "error",
          "no-prototype-builtins": "error",
          "no-redeclare": "error",
          "no-regex-spaces": "error",
          "no-self-assign": "error",
          "no-setter-return": "error",
          "no-shadow-restricted-names": "error",
          "no-sparse-arrays": "error",
          "no-this-before-super": "error",
          "no-unassigned-vars": "error",
          "no-undef": "error",
          "no-unexpected-multiline": "error",
          "no-unreachable": "error",
          "no-unsafe-finally": "error",
          "no-unsafe-negation": "error",
          "no-unsafe-optional-chaining": "error",
          "no-unused-labels": "error",
          "no-unused-private-class-members": "error",
          "no-unused-vars": "error",
          "no-useless-assignment": "error",
          "no-useless-backreference": "error",
          "no-useless-catch": "error",
          "no-useless-escape": "error",
          "no-with": "error",
          "preserve-caught-error": "error",
          "require-yield": "error",
          "use-isnan": "error",
          "valid-typeof": "error",
          "no-array-constructor": "error",
          "no-unused-expressions": "error",
          "typescript/ban-ts-comment": "error",
          "typescript/no-duplicate-enum-values": "error",
          "typescript/no-empty-object-type": "error",
          "typescript/no-explicit-any": "error",
          "typescript/no-extra-non-null-assertion": "error",
          "typescript/no-misused-new": "error",
          "typescript/no-namespace": "error",
          "typescript/no-non-null-asserted-optional-chain": "error",
          "typescript/no-require-imports": "error",
          "typescript/no-this-alias": "error",
          "typescript/no-unnecessary-type-constraint": "error",
          "typescript/no-unsafe-declaration-merging": "error",
          "typescript/no-unsafe-function-type": "error",
          "typescript/no-wrapper-object-types": "error",
          "typescript/prefer-as-const": "error",
          "typescript/prefer-namespace-keyword": "error",
          "typescript/triple-slash-reference": "error",
          "react/rules-of-hooks": "error",
          "react/exhaustive-deps": "warn",
          "react/only-export-components": [
            "error",
            {
              allowConstantExport: true,
            },
          ],
        },
        env: {
          browser: true,
        },
      },
    ],
    options: {
      typeAware: true,
      typeCheck: true,
    },
    jsPlugins: [
      {
        name: "vite-plus",
        specifier: "vite-plus/oxlint-plugin",
      },
    ],
    rules: {
      "vite-plus/prefer-vite-plus-imports": "error",
    },
  },
  plugins: [react(), tailwindcss(), nitro({ serverDir: "server", preset: "vercel" })],
}));
