[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
solc = "0.8.30"
ffi = true
optimizer = true
optimizer_runs = 200
evm_version = "cancun"

remappings = [
  "account-abstraction/=lib/account-abstraction/contracts/",
  "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
  "zknox/=lib/ETHDILITHIUM/src/",
  "sstore2/=lib/ETHDILITHIUM/lib/sstore2/contracts/",
  "InterfaceVerifier/=lib/ETHDILITHIUM/lib/InterfaceVerifier/src/",
  "forge-std/=lib/forge-std/src/",
]

[fmt]
line_length = 100
